# Generated by Django 3.2.18 on 2023-03-26 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="table_number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
