# Generated by Django 3.2.18 on 2023-04-10 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0006_remove_review_booking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="day",
            field=models.DateField(default="10/04/2023"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="time_ordered",
            field=models.DateTimeField(blank=True, default="10/04/2023"),
        ),
        migrations.AlterField(
            model_name="review",
            name="date_posted",
            field=models.DateTimeField(default="10/04/2023"),
        ),
    ]
